### ISSUE TITLE
Incorrect require in spec_helper.rb

### ISSUE THREAD

**Issue by benschumacher** [agaridata/spf-ruby#2]
Look like a small bug in the spec_helper.rb -- it tries to require 'spf-ruby', but it really ought to be require 'spf. I'd offer a pull, but it seems you all aren't interested in contributions.

Cheers!

**Comment by jmehnle** [comment]
Resolved by https://github.com/agaridata/spf-ruby/commit/02966d4400dcee211f5f650faba3d067d417e80f.
