### ISSUE TITLE
invalid multibyte escape with ruby 2.x

### ISSUE THREAD

**Issue by jrideout** [agaridata/spf-ruby#9]
```
spf-0.0.41/lib/spf/util.rb:105: invalid multibyte escape: /([\x00-\x1f\x7f-\xff])/ (SyntaxError)
```

This seems to be fixed by adding `# encoding: US-ASCII` to the file, but I haven't reviewed all the implications

**Comment by jmehnle** [comment]
Resolved by https://github.com/agaridata/spf-ruby/pull/10.
